// Periodic Table Data for AtomLevel Ranking System
// Each element represents a rank, unlocked by XP

const ELEMENTS = [
    // Period 1
    { number: 1, symbol: 'H', name: 'Hydrogen', xpRequired: 0, group: 1, period: 1, category: 'nonmetal', electronConfig: '1s¹', reactivity: 'Highly reactive', fact: 'Most abundant element in the universe' },
    { number: 2, symbol: 'He', name: 'Helium', xpRequired: 100, group: 18, period: 1, category: 'noble-gas', electronConfig: '1s²', reactivity: 'Inert', fact: 'Second lightest element, used in balloons' },
    
    // Period 2
    { number: 3, symbol: 'Li', name: 'Lithium', xpRequired: 250, group: 1, period: 2, category: 'alkali-metal', electronConfig: '[He] 2s¹', reactivity: 'Very reactive', fact: 'Lightest metal, used in batteries' },
    { number: 4, symbol: 'Be', name: 'Beryllium', xpRequired: 450, group: 2, period: 2, category: 'alkaline-earth', electronConfig: '[He] 2s²', reactivity: 'Moderately reactive', fact: 'Used in aerospace materials' },
    { number: 5, symbol: 'B', name: 'Boron', xpRequired: 700, group: 13, period: 2, category: 'metalloid', electronConfig: '[He] 2s² 2p¹', reactivity: 'Low reactivity', fact: 'Essential for plant growth' },
    { number: 6, symbol: 'C', name: 'Carbon', xpRequired: 1000, group: 14, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p²', reactivity: 'Moderate', fact: 'Basis of all organic life' },
    { number: 7, symbol: 'N', name: 'Nitrogen', xpRequired: 1350, group: 15, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p³', reactivity: 'Low reactivity', fact: '78% of Earth\'s atmosphere' },
    { number: 8, symbol: 'O', name: 'Oxygen', xpRequired: 1750, group: 16, period: 2, category: 'nonmetal', electronConfig: '[He] 2s² 2p⁴', reactivity: 'Highly reactive', fact: 'Essential for respiration' },
    { number: 9, symbol: 'F', name: 'Fluorine', xpRequired: 2200, group: 17, period: 2, category: 'halogen', electronConfig: '[He] 2s² 2p⁵', reactivity: 'Most reactive element', fact: 'Used in toothpaste' },
    { number: 10, symbol: 'Ne', name: 'Neon', xpRequired: 2700, group: 18, period: 2, category: 'noble-gas', electronConfig: '[He] 2s² 2p⁶', reactivity: 'Inert', fact: 'Creates bright red-orange glow in signs' },
    
    // Period 3
    { number: 11, symbol: 'Na', name: 'Sodium', xpRequired: 3250, group: 1, period: 3, category: 'alkali-metal', electronConfig: '[Ne] 3s¹', reactivity: 'Very reactive', fact: 'Essential electrolyte in human body' },
    { number: 12, symbol: 'Mg', name: 'Magnesium', xpRequired: 3850, group: 2, period: 3, category: 'alkaline-earth', electronConfig: '[Ne] 3s²', reactivity: 'Moderately reactive', fact: 'Burns with brilliant white light' },
    { number: 13, symbol: 'Al', name: 'Aluminum', xpRequired: 4500, group: 13, period: 3, category: 'post-transition', electronConfig: '[Ne] 3s² 3p¹', reactivity: 'Moderate', fact: 'Most abundant metal in Earth\'s crust' },
    { number: 14, symbol: 'Si', name: 'Silicon', xpRequired: 5200, group: 14, period: 3, category: 'metalloid', electronConfig: '[Ne] 3s² 3p²', reactivity: 'Low', fact: 'Foundation of computer chips' },
    { number: 15, symbol: 'P', name: 'Phosphorus', xpRequired: 5950, group: 15, period: 3, category: 'nonmetal', electronConfig: '[Ne] 3s² 3p³', reactivity: 'Reactive', fact: 'Essential for DNA and ATP' },
    { number: 16, symbol: 'S', name: 'Sulfur', xpRequired: 6750, group: 16, period: 3, category: 'nonmetal', electronConfig: '[Ne] 3s² 3p⁴', reactivity: 'Moderate', fact: 'Gives rotten eggs their smell' },
    { number: 17, symbol: 'Cl', name: 'Chlorine', xpRequired: 7600, group: 17, period: 3, category: 'halogen', electronConfig: '[Ne] 3s² 3p⁵', reactivity: 'Very reactive', fact: 'Used to disinfect water' },
    { number: 18, symbol: 'Ar', name: 'Argon', xpRequired: 8500, group: 18, period: 3, category: 'noble-gas', electronConfig: '[Ne] 3s² 3p⁶', reactivity: 'Inert', fact: 'Used in light bulbs' },
    
    // Period 4
    { number: 19, symbol: 'K', name: 'Potassium', xpRequired: 9450, group: 1, period: 4, category: 'alkali-metal', electronConfig: '[Ar] 4s¹', reactivity: 'Very reactive', fact: 'Essential for nerve function' },
    { number: 20, symbol: 'Ca', name: 'Calcium', xpRequired: 10450, group: 2, period: 4, category: 'alkaline-earth', electronConfig: '[Ar] 4s²', reactivity: 'Moderately reactive', fact: 'Builds strong bones and teeth' },
    { number: 21, symbol: 'Sc', name: 'Scandium', xpRequired: 11500, group: 3, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹ 4s²', reactivity: 'Moderate', fact: 'Used in aerospace alloys' },
    { number: 22, symbol: 'Ti', name: 'Titanium', xpRequired: 12600, group: 4, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d² 4s²', reactivity: 'Low', fact: 'Strong, lightweight, corrosion-resistant' },
    { number: 23, symbol: 'V', name: 'Vanadium', xpRequired: 13750, group: 5, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d³ 4s²', reactivity: 'Moderate', fact: 'Strengthens steel' },
    { number: 24, symbol: 'Cr', name: 'Chromium', xpRequired: 14950, group: 6, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁵ 4s¹', reactivity: 'Low', fact: 'Makes stainless steel stainless' },
    { number: 25, symbol: 'Mn', name: 'Manganese', xpRequired: 16200, group: 7, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁵ 4s²', reactivity: 'Moderate', fact: 'Essential for photosynthesis' },
    { number: 26, symbol: 'Fe', name: 'Iron', xpRequired: 17500, group: 8, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁶ 4s²', reactivity: 'Moderate', fact: 'Most common element on Earth by mass' },
    { number: 27, symbol: 'Co', name: 'Cobalt', xpRequired: 18850, group: 9, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁷ 4s²', reactivity: 'Moderate', fact: 'Used in rechargeable batteries' },
    { number: 28, symbol: 'Ni', name: 'Nickel', xpRequired: 20250, group: 10, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d⁸ 4s²', reactivity: 'Low', fact: 'Used in coins and stainless steel' },
    { number: 29, symbol: 'Cu', name: 'Copper', xpRequired: 21700, group: 11, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹⁰ 4s¹', reactivity: 'Low', fact: 'Excellent conductor of electricity' },
    { number: 30, symbol: 'Zn', name: 'Zinc', xpRequired: 23200, group: 12, period: 4, category: 'transition-metal', electronConfig: '[Ar] 3d¹⁰ 4s²', reactivity: 'Moderate', fact: 'Essential for immune system' },
    { number: 31, symbol: 'Ga', name: 'Gallium', xpRequired: 24750, group: 13, period: 4, category: 'post-transition', electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', reactivity: 'Moderate', fact: 'Melts in your hand (29.8°C)' },
    { number: 32, symbol: 'Ge', name: 'Germanium', xpRequired: 26350, group: 14, period: 4, category: 'metalloid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', reactivity: 'Low', fact: 'Used in semiconductors' },
    { number: 33, symbol: 'As', name: 'Arsenic', xpRequired: 28000, group: 15, period: 4, category: 'metalloid', electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', reactivity: 'Moderate', fact: 'Toxic, but used in some medicines' },
    { number: 34, symbol: 'Se', name: 'Selenium', xpRequired: 29700, group: 16, period: 4, category: 'nonmetal', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', reactivity: 'Moderate', fact: 'Essential trace element' },
    { number: 35, symbol: 'Br', name: 'Bromine', xpRequired: 31450, group: 17, period: 4, category: 'halogen', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', reactivity: 'Very reactive', fact: 'Only liquid nonmetal at room temp' },
    { number: 36, symbol: 'Kr', name: 'Krypton', xpRequired: 33250, group: 18, period: 4, category: 'noble-gas', electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', reactivity: 'Inert', fact: 'Used in high-performance light bulbs' },
    
    // Period 5 (continuing with exponential XP growth)
    { number: 37, symbol: 'Rb', name: 'Rubidium', xpRequired: 35100, group: 1, period: 5, category: 'alkali-metal', electronConfig: '[Kr] 5s¹', reactivity: 'Very reactive', fact: 'Ignites spontaneously in air' },
    { number: 38, symbol: 'Sr', name: 'Strontium', xpRequired: 37000, group: 2, period: 5, category: 'alkaline-earth', electronConfig: '[Kr] 5s²', reactivity: 'Very reactive', fact: 'Creates red fireworks' },
    { number: 39, symbol: 'Y', name: 'Yttrium', xpRequired: 38950, group: 3, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹ 5s²', reactivity: 'Moderate', fact: 'Used in LED lights' },
    { number: 40, symbol: 'Zr', name: 'Zirconium', xpRequired: 40950, group: 4, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d² 5s²', reactivity: 'Low', fact: 'Extremely corrosion-resistant' },
    { number: 41, symbol: 'Nb', name: 'Niobium', xpRequired: 43000, group: 5, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁴ 5s¹', reactivity: 'Low', fact: 'Used in superconducting magnets' },
    { number: 42, symbol: 'Mo', name: 'Molybdenum', xpRequired: 45100, group: 6, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁵ 5s¹', reactivity: 'Low', fact: 'Strengthens steel at high temps' },
    { number: 43, symbol: 'Tc', name: 'Technetium', xpRequired: 47250, group: 7, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁵ 5s²', reactivity: 'Moderate', fact: 'First artificially produced element' },
    { number: 44, symbol: 'Ru', name: 'Ruthenium', xpRequired: 49450, group: 8, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁷ 5s¹', reactivity: 'Low', fact: 'Used in chip resistors' },
    { number: 45, symbol: 'Rh', name: 'Rhodium', xpRequired: 51700, group: 9, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d⁸ 5s¹', reactivity: 'Low', fact: 'Most expensive precious metal' },
    { number: 46, symbol: 'Pd', name: 'Palladium', xpRequired: 54000, group: 10, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰', reactivity: 'Low', fact: 'Absorbs hydrogen like a sponge' },
    { number: 47, symbol: 'Ag', name: 'Silver', xpRequired: 56350, group: 11, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰ 5s¹', reactivity: 'Low', fact: 'Best conductor of electricity' },
    { number: 48, symbol: 'Cd', name: 'Cadmium', xpRequired: 58750, group: 12, period: 5, category: 'transition-metal', electronConfig: '[Kr] 4d¹⁰ 5s²', reactivity: 'Moderate', fact: 'Used in rechargeable batteries' },
    { number: 49, symbol: 'In', name: 'Indium', xpRequired: 61200, group: 13, period: 5, category: 'post-transition', electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', reactivity: 'Moderate', fact: 'Used in touchscreens' },
    { number: 50, symbol: 'Sn', name: 'Tin', xpRequired: 63700, group: 14, period: 5, category: 'post-transition', electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', reactivity: 'Low', fact: 'Used in solder and tin cans' },
    { number: 51, symbol: 'Sb', name: 'Antimony', xpRequired: 66250, group: 15, period: 5, category: 'metalloid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', reactivity: 'Moderate', fact: 'Used in flame retardants' },
    { number: 52, symbol: 'Te', name: 'Tellurium', xpRequired: 68850, group: 16, period: 5, category: 'metalloid', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', reactivity: 'Moderate', fact: 'Used in solar panels' },
    { number: 53, symbol: 'I', name: 'Iodine', xpRequired: 71500, group: 17, period: 5, category: 'halogen', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', reactivity: 'Reactive', fact: 'Essential for thyroid function' },
    { number: 54, symbol: 'Xe', name: 'Xenon', xpRequired: 74200, group: 18, period: 5, category: 'noble-gas', electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', reactivity: 'Inert', fact: 'Used in high-intensity lamps' },
    
    // Period 6 (lanthanides included)
    { number: 55, symbol: 'Cs', name: 'Cesium', xpRequired: 77000, group: 1, period: 6, category: 'alkali-metal', electronConfig: '[Xe] 6s¹', reactivity: 'Extremely reactive', fact: 'Most reactive metal' },
    { number: 56, symbol: 'Ba', name: 'Barium', xpRequired: 79900, group: 2, period: 6, category: 'alkaline-earth', electronConfig: '[Xe] 6s²', reactivity: 'Very reactive', fact: 'Creates green fireworks' },
    { number: 57, symbol: 'La', name: 'Lanthanum', xpRequired: 82900, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 5d¹ 6s²', reactivity: 'Moderate', fact: 'First lanthanide element' },
    { number: 58, symbol: 'Ce', name: 'Cerium', xpRequired: 86000, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹ 5d¹ 6s²', reactivity: 'Moderate', fact: 'Most abundant rare earth element' },
    { number: 59, symbol: 'Pr', name: 'Praseodymium', xpRequired: 89200, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f³ 6s²', reactivity: 'Moderate', fact: 'Creates yellow-green glass' },
    { number: 60, symbol: 'Nd', name: 'Neodymium', xpRequired: 92500, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁴ 6s²', reactivity: 'Moderate', fact: 'Strongest permanent magnets' },
    { number: 61, symbol: 'Pm', name: 'Promethium', xpRequired: 95900, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁵ 6s²', reactivity: 'Moderate', fact: 'Only radioactive lanthanide' },
    { number: 62, symbol: 'Sm', name: 'Samarium', xpRequired: 99400, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁶ 6s²', reactivity: 'Moderate', fact: 'Used in cancer treatment' },
    { number: 63, symbol: 'Eu', name: 'Europium', xpRequired: 103000, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁷ 6s²', reactivity: 'Moderate', fact: 'Used in euro banknote security' },
    { number: 64, symbol: 'Gd', name: 'Gadolinium', xpRequired: 106700, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', reactivity: 'Moderate', fact: 'Used in MRI contrast agents' },
    { number: 65, symbol: 'Tb', name: 'Terbium', xpRequired: 110500, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f⁹ 6s²', reactivity: 'Moderate', fact: 'Creates green phosphors' },
    { number: 66, symbol: 'Dy', name: 'Dysprosium', xpRequired: 114400, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁰ 6s²', reactivity: 'Moderate', fact: 'Used in lasers' },
    { number: 67, symbol: 'Ho', name: 'Holmium', xpRequired: 118400, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹¹ 6s²', reactivity: 'Moderate', fact: 'Strongest magnetic field' },
    { number: 68, symbol: 'Er', name: 'Erbium', xpRequired: 122500, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹² 6s²', reactivity: 'Moderate', fact: 'Colors glass pink' },
    { number: 69, symbol: 'Tm', name: 'Thulium', xpRequired: 126700, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹³ 6s²', reactivity: 'Moderate', fact: 'Rarest stable lanthanide' },
    { number: 70, symbol: 'Yb', name: 'Ytterbium', xpRequired: 131000, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁴ 6s²', reactivity: 'Moderate', fact: 'Used in atomic clocks' },
    { number: 71, symbol: 'Lu', name: 'Lutetium', xpRequired: 135400, group: 3, period: 6, category: 'lanthanide', electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', reactivity: 'Moderate', fact: 'Hardest lanthanide' },
    { number: 72, symbol: 'Hf', name: 'Hafnium', xpRequired: 139900, group: 4, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', reactivity: 'Low', fact: 'Used in nuclear reactors' },
    { number: 73, symbol: 'Ta', name: 'Tantalum', xpRequired: 144500, group: 5, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', reactivity: 'Low', fact: 'Extremely corrosion-resistant' },
    { number: 74, symbol: 'W', name: 'Tungsten', xpRequired: 149200, group: 6, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', reactivity: 'Low', fact: 'Highest melting point of metals' },
    { number: 75, symbol: 'Re', name: 'Rhenium', xpRequired: 154000, group: 7, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', reactivity: 'Low', fact: 'Third highest melting point' },
    { number: 76, symbol: 'Os', name: 'Osmium', xpRequired: 158900, group: 8, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', reactivity: 'Low', fact: 'Densest naturally occurring element' },
    { number: 77, symbol: 'Ir', name: 'Iridium', xpRequired: 163900, group: 9, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', reactivity: 'Low', fact: 'Most corrosion-resistant metal' },
    { number: 78, symbol: 'Pt', name: 'Platinum', xpRequired: 169000, group: 10, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', reactivity: 'Low', fact: 'Used in catalytic converters' },
    { number: 79, symbol: 'Au', name: 'Gold', xpRequired: 174200, group: 11, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', reactivity: 'Very low', fact: 'Most malleable metal' },
    { number: 80, symbol: 'Hg', name: 'Mercury', xpRequired: 179500, group: 12, period: 6, category: 'transition-metal', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', reactivity: 'Low', fact: 'Only liquid metal at room temp' },
    { number: 81, symbol: 'Tl', name: 'Thallium', xpRequired: 184900, group: 13, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', reactivity: 'Moderate', fact: 'Highly toxic' },
    { number: 82, symbol: 'Pb', name: 'Lead', xpRequired: 190400, group: 14, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', reactivity: 'Low', fact: 'Dense, soft, and toxic' },
    { number: 83, symbol: 'Bi', name: 'Bismuth', xpRequired: 196000, group: 15, period: 6, category: 'post-transition', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', reactivity: 'Low', fact: 'Most diamagnetic element' },
    { number: 84, symbol: 'Po', name: 'Polonium', xpRequired: 201700, group: 16, period: 6, category: 'metalloid', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', reactivity: 'Moderate', fact: 'Extremely radioactive' },
    { number: 85, symbol: 'At', name: 'Astatine', xpRequired: 207500, group: 17, period: 6, category: 'halogen', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', reactivity: 'Reactive', fact: 'Rarest naturally occurring element' },
    { number: 86, symbol: 'Rn', name: 'Radon', xpRequired: 213400, group: 18, period: 6, category: 'noble-gas', electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', reactivity: 'Inert', fact: 'Radioactive noble gas' },
    
    // Period 7 (actinides included)
    { number: 87, symbol: 'Fr', name: 'Francium', xpRequired: 219400, group: 1, period: 7, category: 'alkali-metal', electronConfig: '[Rn] 7s¹', reactivity: 'Extremely reactive', fact: 'Most unstable of first 101 elements' },
    { number: 88, symbol: 'Ra', name: 'Radium', xpRequired: 225500, group: 2, period: 7, category: 'alkaline-earth', electronConfig: '[Rn] 7s²', reactivity: 'Very reactive', fact: 'Glows in the dark' },
    { number: 89, symbol: 'Ac', name: 'Actinium', xpRequired: 231700, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 6d¹ 7s²', reactivity: 'Moderate', fact: 'First actinide element' },
    { number: 90, symbol: 'Th', name: 'Thorium', xpRequired: 238000, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 6d² 7s²', reactivity: 'Moderate', fact: 'Potential nuclear fuel' },
    { number: 91, symbol: 'Pa', name: 'Protactinium', xpRequired: 244400, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f² 6d¹ 7s²', reactivity: 'Moderate', fact: 'Extremely rare' },
    { number: 92, symbol: 'U', name: 'Uranium', xpRequired: 250900, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f³ 6d¹ 7s²', reactivity: 'Moderate', fact: 'Used in nuclear power' },
    { number: 93, symbol: 'Np', name: 'Neptunium', xpRequired: 257500, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', reactivity: 'Moderate', fact: 'First transuranium element' },
    { number: 94, symbol: 'Pu', name: 'Plutonium', xpRequired: 264200, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁶ 7s²', reactivity: 'Moderate', fact: 'Used in nuclear weapons' },
    { number: 95, symbol: 'Am', name: 'Americium', xpRequired: 271000, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁷ 7s²', reactivity: 'Moderate', fact: 'Used in smoke detectors' },
    { number: 96, symbol: 'Cm', name: 'Curium', xpRequired: 277900, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', reactivity: 'Moderate', fact: 'Named after Marie Curie' },
    { number: 97, symbol: 'Bk', name: 'Berkelium', xpRequired: 284900, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f⁹ 7s²', reactivity: 'Moderate', fact: 'Named after Berkeley, California' },
    { number: 98, symbol: 'Cf', name: 'Californium', xpRequired: 292000, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁰ 7s²', reactivity: 'Moderate', fact: 'Powerful neutron emitter' },
    { number: 99, symbol: 'Es', name: 'Einsteinium', xpRequired: 299200, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹¹ 7s²', reactivity: 'Moderate', fact: 'Named after Albert Einstein' },
    { number: 100, symbol: 'Fm', name: 'Fermium', xpRequired: 306500, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹² 7s²', reactivity: 'Moderate', fact: 'Named after Enrico Fermi' },
    { number: 101, symbol: 'Md', name: 'Mendelevium', xpRequired: 313900, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹³ 7s²', reactivity: 'Moderate', fact: 'Named after Mendeleev' },
    { number: 102, symbol: 'No', name: 'Nobelium', xpRequired: 321400, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁴ 7s²', reactivity: 'Moderate', fact: 'Named after Alfred Nobel' },
    { number: 103, symbol: 'Lr', name: 'Lawrencium', xpRequired: 329000, group: 3, period: 7, category: 'actinide', electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', reactivity: 'Moderate', fact: 'Last actinide element' },
    { number: 104, symbol: 'Rf', name: 'Rutherfordium', xpRequired: 336700, group: 4, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', reactivity: 'Unknown', fact: 'Named after Ernest Rutherford' },
    { number: 105, symbol: 'Db', name: 'Dubnium', xpRequired: 344500, group: 5, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', reactivity: 'Unknown', fact: 'Named after Dubna, Russia' },
    { number: 106, symbol: 'Sg', name: 'Seaborgium', xpRequired: 352400, group: 6, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', reactivity: 'Unknown', fact: 'Named after Glenn Seaborg' },
    { number: 107, symbol: 'Bh', name: 'Bohrium', xpRequired: 360400, group: 7, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', reactivity: 'Unknown', fact: 'Named after Niels Bohr' },
    { number: 108, symbol: 'Hs', name: 'Hassium', xpRequired: 368500, group: 8, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', reactivity: 'Unknown', fact: 'Named after Hesse, Germany' },
    { number: 109, symbol: 'Mt', name: 'Meitnerium', xpRequired: 376700, group: 9, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', reactivity: 'Unknown', fact: 'Named after Lise Meitner' },
    { number: 110, symbol: 'Ds', name: 'Darmstadtium', xpRequired: 385000, group: 10, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s¹', reactivity: 'Unknown', fact: 'Named after Darmstadt, Germany' },
    { number: 111, symbol: 'Rg', name: 'Roentgenium', xpRequired: 393400, group: 11, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹', reactivity: 'Unknown', fact: 'Named after Wilhelm Röntgen' },
    { number: 112, symbol: 'Cn', name: 'Copernicium', xpRequired: 401900, group: 12, period: 7, category: 'transition-metal', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', reactivity: 'Unknown', fact: 'Named after Nicolaus Copernicus' },
    { number: 113, symbol: 'Nh', name: 'Nihonium', xpRequired: 410500, group: 13, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', reactivity: 'Unknown', fact: 'First element discovered in Asia' },
    { number: 114, symbol: 'Fl', name: 'Flerovium', xpRequired: 419200, group: 14, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', reactivity: 'Unknown', fact: 'Named after Georgy Flyorov' },
    { number: 115, symbol: 'Mc', name: 'Moscovium', xpRequired: 428000, group: 15, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', reactivity: 'Unknown', fact: 'Named after Moscow, Russia' },
    { number: 116, symbol: 'Lv', name: 'Livermorium', xpRequired: 436900, group: 16, period: 7, category: 'post-transition', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', reactivity: 'Unknown', fact: 'Named after Livermore, California' },
    { number: 117, symbol: 'Ts', name: 'Tennessine', xpRequired: 445900, group: 17, period: 7, category: 'halogen', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', reactivity: 'Unknown', fact: 'Named after Tennessee' },
    { number: 118, symbol: 'Og', name: 'Oganesson', xpRequired: 455000, group: 18, period: 7, category: 'noble-gas', electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', reactivity: 'Unknown', fact: 'Heaviest known element' }
];

// Category colors for periodic table
const CATEGORY_COLORS = {
    'alkali-metal': '#ff6b6b',
    'alkaline-earth': '#ffd93d',
    'transition-metal': '#6bcf7f',
    'post-transition': '#4ecdc4',
    'metalloid': '#95e1d3',
    'nonmetal': '#a8e6cf',
    'halogen': '#ff8b94',
    'noble-gas': '#c7ceea',
    'lanthanide': '#ffaaa5',
    'actinide': '#ff8c94'
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ELEMENTS, CATEGORY_COLORS };
}
